apiVersion: v1
kind: Pod
metadata:
  name: two-containers-pod
spec:
  containers:
  - name: alpine
    image: alpine:3.2
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"