apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    tier: frontend
spec:
  containers:
  - name: alpine
    image: alpine:3.2
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
