apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  hostname: busybox
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox
