apiVersion: v1
kind: Service
metadata:
  name: svc-node-port
  labels:
    app: nginx
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
  type: NodePort
